/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 3-smile.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3-smile.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.048, 1.413, 0.081]} scale={0.254}>
        <mesh geometry={nodes.BezierCurve328.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.BezierCurve328_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.BezierCurve328_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.BezierCurve328_3.geometry} material={materials.Material} />
        <mesh geometry={nodes.BezierCurve328_4.geometry} material={materials.material_78} />
        <mesh geometry={nodes.BezierCurve328_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.BezierCurve328_6.geometry} material={materials.PURPLE} />
      </group>
    </group>
  )
}

useGLTF.preload('/3-smile.glb')
