/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 v1-mesh.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/v1-mesh.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1, 0]}>
        <mesh geometry={nodes.BezierCurve016.geometry} material={materials.Material} />
        <mesh geometry={nodes.BezierCurve016_1.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.BezierCurve016_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.BezierCurve016_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.BezierCurve016_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.BezierCurve016_5.geometry} material={materials['teeth.003']} />
        <mesh geometry={nodes.BezierCurve016_6.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.BezierCurve016_7.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.BezierCurve016_8.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.BezierCurve016_9.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/v1-mesh.glb')
